Add note about python2 vs 3
Although I tried to standardize alll the nyc-db scripts to
use python3 instead of python2.

This script raised this error with python3 but not python2:

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7737: ordinal not in range(128)